### ISSUE TITLE
Implement MsBackendDataFrame

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#12]
Implement the in-memory backend.

**Comment by jorainer** [comment]
Basic class implemented. Remains to implement all required methods and add unit tests for them.

**Comment by jorainer** [comment]
Rename that backend into `MsBackendDataFrame` (issue #9 )

**Comment by lgatto** [comment]
@jorainer - have you renamed this in your own branch? If so, could you merge?

**Comment by jorainer** [comment]
@lgatto , no, please wait for the pull request. I still have to finish implementing the last methods and add the related unit tests.

**Comment by lgatto** [comment]
I have done some updates to MsBachend, mostly man, haven't touched anything else.

**Comment by jorainer** [comment]
For the `MsBackendDataFrame` I would like the current implementation that does **not** initialize the `@spectraData` `DataFrame` with all supported columns but the accessors would take care of creating eventually missing data on-the-fly. An example accessor is shown below:

```r
setMethod("precScanNum", "MsBackendDataFrame", function(object) {
    if (any(colnames(object@spectraData) == "precScanNum"))
        object@spectraData$precScanNum
    else rep(NA_integer_, times = length(object))
})
```

My two main reasons why I think that this is a good implementation are:
1) we don't need to allocate memory for something that is not there. Keeps memory demand low.
2) the object is more flexible and is inherently backwards compatible (or forward compatible?): assume we require the `MsBackendDataFrame` to have all mandatory columns in its `@spectraData` `DataFrame` to be always initialized and present and a user saves a `MsBackendDataFrame` object to disk. When we add a field/variable to the list of mandatory columns in an updated version of the package, this column will be missing in the saved version and the user will get an error. Now, for the current implementation that creates missing column content on the fly that would be no problem at all. This would make maintanence much simpler, as we don't have to be carefull with class versions, updating objects etc.

Any thoughts on that @lgatto @sgibb ?

**Comment by lgatto** [comment]
I am not convinced by 1, but you win me over with 2.
