### ISSUE TITLE
importFrom syntax

### ISSUE THREAD

**Issue by lgatto** [lgatto/Spectra#15]
@jorainer could you explain [this](https://github.com/lgatto/Spectra/blob/f834d8f5cd691e0dd785bd0afdca769e044be46d/R/MsBackend.R#L261) `importFrom` syntax. I understand `@importFrom methods .valueClassTest`, which is also reflected in the `NAMESPACE`, but I'm confused about the rest of the line `is new validObject` that reads like a comment.

**Comment by jorainer** [comment]
Funny, indeed the `is new validObject` sounds like a real sentence. But no, the `importFrom` syntax is `importFrom <package> <function1> <function2> <function3>...`. So in this case it is importing also `is`, `new` and `validObject` from `methods`.
