### ISSUE TITLE
Implement a MsBackendRleDataFrame

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#18]
The idea comes from https://github.com/lgatto/Spectra/issues/11#issuecomment-484444986 to have an additional *in-memory* backend that compresses its content by using `Rle` for columns where it makes sense. The `MsBackendMzR` could then extend this class instead of the `MsBackendDataFrame` to reduce its memory demand.

In addition, the `MsBackendRleDataFrame` would, as the `MsBackendDataFrame` (https://github.com/lgatto/Spectra/issues/12#issuecomment-484423562), create content for missing mandatory columns on-the-fly.

**Comment by lgatto** [comment]
I would prefer not to go down that route, as it complexities the code and the design for users and other maintainers. 

Let go for a `MsBackendDataFrame` that generates mandatory data on the fly.

`MsBackendMzR` can use `Rle` if this proves useful.
