### ISSUE TITLE
Definition of the new `Spectra` object

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#2]
The new `Spectra` object should be completely independent of the `Spectrum` objects. The `spectraData` should contain all spectrum related information.

**Comment by jorainer** [comment]
There are two possibilities I think:

- Option 1) (implementation we had in `MSnbase`)

```r
setClass(
    "Spectra",
    slots = c(
        backend = "Backend",
        spectraData = "DataFrame",
        processingQueue = "list",
        ## logging
        processing = "character",
        ## metadata
        metadata = "list",
        version = "character"
    ),
    prototype = prototype(version = "0.1"),
    validity = .validSpectra
)
```

- Option 2)

```r
setClass(
    "Spectra",
    contains = "DataFrame",
    slots = c(
        backend = "Backend",
        processingQueue = "list",
        ## logging
        processing = "character",
        ## metadata
        metadata = "list",
        version = "character"
    ),
    prototype = prototype(version = "0.1"),
    validity = .validSpectra
)
```

I'm not quite sure which one would be better - for the second one we could re-use `DataFrame` methods out of the box but we have then the explicit dependency of the `DataFrame`. Any preferences @sgibb @lgatto ?

**Comment by lgatto** [comment]
- Important to highlight that M/Z and intensities would be columns in the `DataFrame` here. (But see last point here)
- I would prefer option 1, as I don't really thing that we extend `DataFrame`. Although it's not clear to me what the benefits of inheriting its methods would be.
- In addition to this, and possibly the most important, are the required methods for `Spectra` objects: `mz`, `intensity`, ... probably deserves its own issue.
- But most importantly, is this `DataFrame` really needed? Would the `DataFrame` not be part of an *in memory* backend? Should the `Spectra` class not only define the preprocessing and logging infrastructure, the backend, and the interface through a set of mandatory and optional methods?

**Comment by lgatto** [comment]
Following up from my last point, would something like this be workable (see #5 regarding backend naming)
```r
setClass(
    "Spectra",
    slots = c(
        backend = "MsBackend",
        processingQueue = "list",
        ## logging
        processing = "character",
        ## metadata
        metadata = "list",
        version = "character"
    ),
    prototype = prototype(version = "0.1"),
    validity = .validSpectra
)
```
And with an example backend being
```r
setClass("MsBackendDataFrame",
         contains = "MsBackend",
         spectraData = "DataFrame")

## with, for example
setMethod("mz", "MsBackendDataFrame",
          function(object, ...) object@spectraData$mz)
```

```r
setClass("MsBackendSpectrum",
         contains = "MsBackend",
         spectra = "environment",
         spectraData = "DataFrame")

## with, for example
setMethod("mz", "MsBackendSpectrum",
                    function(object, ...) lapply(spectra(objec), function(obj) obj@mz))
```
The dispatching would be defined based on the backend, but I believe this was already explicit beforehand.

**Comment by jorainer** [comment]
I see the point. Having part of the data (header information) in the `Spectra` and part of it (m/z and intensity values) in the `Backend` does not seem to be a good design. So, if I understood it correctly, each `MsBackend` is supposed to hold **all** the MS data, while the `Spectra` is sort of the interface for the user.

I have to think a bit over it (especially if and how that would work for database backends) but it seems to be more practicable.

Now, things we need to ensure are:

- Arbitrary annotations/columns can be added to each `Spectra` (and thus `MsBackend`).
- `spectrapply` method with a parameter `fcol` to define how to perform parallel processing.

**Comment by lgatto** [comment]
Actually, I think it should be the backend's choice how/where to store the data, whether it's header, mz or intensity data. The `Spectra` contract defines the accessors that need to be defined by the backend.
