### ISSUE TITLE
Add a filter function and AnnotationFilter filters

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#21]
Add a `filter` method to filter `Spectra` objects based on `AnnotationFilter` classes. First useful filters will be:
- [ ] `MsLevelFilter`
- [ ] `MzRangeFilter`
- [ ] `RtimeRangeFilter`

At first, subsetting using `[x$msLevel == 1]` might seem the more straightforward operation, but the `filter` would be beneficial for any database backend as it does not require the data to be in memory: the filter could be translated to sql.

**Comment by lgatto** [comment]
I fail to see how defining `AnnotationFilter` derived classe will be useful for `Spectra` objects.

**Comment by jorainer** [comment]
It's something I would like to test. The only benefit I see will be for backends that don't keep all information, like the MS level of all spectra in memory. I could imagine a database backend that you could ask to return all spectra with MS level 1. For such a scenario the `AnnotationFilter` approach *could* be useful. 

But filters should definitely not overcomplicate things.

**Comment by jorainer** [comment]
The only advantage I can see is with some more complicated filters such as `~ ms_level > 1 & rtime < 34`, but the `filter*` methods are easier to implement (and to understand). Eventually we could add this later as a fancy addon.
