### ISSUE TITLE
Add ProcessingStep object and related functionality

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#3]
Add the `ProcessingStep` class and all related functionality.

**Comment by jorainer** [comment]
Done

**Comment by sgibb** [comment]
This may be a stupid question and please be aware that I had not enough time to go through all the code yet: isn't the purpose of this package to provide a low-level interface for MS **data**? Should be `ProcessingStep` stay in `MSnbase`?
IMHO it just requires `backendSplitByFile`, `backendReadSpectra` and `backendWriteSpectra`. I am not sure how we will define the interface or if we really want to provide public access to `backendReadSpectra`/`backendWriteSpectra` but spectra *processing* should be done in `MSnbase`, or?

**Comment by jorainer** [comment]
Good point. Yes, I also think that we should focus on data accessors and similar in `Spectra`. But I also think that the `Spectra` class should provide all the necessary things to enable lazy processing, and thus we also need the `ProcessingStep` class. So `Spectra` should not only contain backend definitions, but also the `Spectra` class, which is somehow similar to the `MSnExperiment` class we had defined in the *backends* branch in `MSnbase`.
