### ISSUE TITLE
Definition of the new `MsBackend` class

### ISSUE THREAD

**Issue by jorainer** [lgatto/Spectra#8]
This issue is to discuss the basic backend architecture and goes along with issue #4 (required methods for backend and `Spectra`).

My proposal would be to define the following base `MsBackend` class:

```r
setClass(
    "MsBackend",
    slots = c(
        spectraData = "DataFrame",
        files = "character",
        modCounter = "integer",
        version = "character"
    ),
    prototype = prototype(spectraData = DataFrame(),
        version = "0.1",
        files = character(),
        modCounter = integer()),
    validity = .validMsBackend
)
```

We could then implement all accessor methods for that backend and would not have to re-implement most of them for most other backends.

`spectraData` would have also columns `mz` and `intensity` with the m/z and intensity values. `.validMsBackend` would check the `spectraData` that, for columns that are present (would not make all columns mandatory), they contain the expected data types.

If you @sgibb and @lgatto agree, I would give that implementation a shot in the *jomaster* branch.

**Comment by lgatto** [comment]
I am not convinced with the `spectraData` slot. I think that we need a `spectraData` accessor that returns a `DataFrame` but don't need the corresponding slot. And we also need `mz` and `intensity` accessors that return lists of numerics (see #4), without saying where these things live.

Also, shouldn't we make it virtual?

**Comment by jorainer** [comment]
I don't see the benefit of making the class virtual. I would implement the basic backend (which is an in-memory backend) as outlined above. on-disk backends can extend that one. Most backends will need a `spectraData` `DataFrame` to keep some sort of information about the content so I think it would make sense to have it as a dedicated slot (it would also not hurt, because it could also be empty if not needed). 

Examples are the `MsBackendMzR` and the `MsBackendHdf5`, for both we will want to keep part of the data in memory. They need therefore a `spectraData` `DataFrame`, so IMHO it would be good to have it already in the base class to avoid the need for re-implementation of the slot and associated methods in the two classes.

Example implementations for backend methods would then be:
```
setMethod("msLevel", "MsBackend", function(object) {
    if (any(colnames(object@spectraData) == "msLevel"))
         object@spectraData$msLevel
    else rep(NA_integer_, times = nrow(object@spectraData))
})
```

This would enable us to keep the `DataFrame` lightweight, because we don't necessarily need a column for all slots that we had in the `Spectrum` objects.

I will work on it and provide some examples that we can then discuss in the pull request.

**Comment by jorainer** [comment]
Update: we're removing the `@spectraData` slot, add a `@readonly` slot and make the class virtual.

**Comment by sgibb** [comment]
> Example implementations for backend methods would then be:
```r
setMethod("msLevel", "MsBackend", function(object) {
    if (any(colnames(object@spectraData) == "msLevel"))
         object@spectraData$msLevel
    else rep(NA_integer_, times = nrow(object@spectraData))
})

What about the following method:
```r
setMethod("header", "MsBackend", function(object, field, returnValue) {
   stop(...)
})

setMethod("header", "MsBackendDataFrame", function(object, field, returnValue) {
    if (is.null(object@spectraData[[field]]))
        rep_len(returnValue, length(object))
    else
        object@spectraData[[field]]
}
```
instead of `msLevel`, `precursorCharge`, `precursorIntensity`, ... for each backend (see my comment in `MSnbase`: https://github.com/lgatto/MSnbase/pull/449#discussion_r261818051)

For the `Spectra` class we could then use:
```r
setMethod("msLevel", "Spectra", function(object) {
    header(object@backend, "msLevel", NA_integer)
})
# ... and so on
```
This would reduce a lot of code lines and IMHO simplifies the interface.

For the old `Spectrum` based classes it would be a little bit ugly:
```r
setMethod("header", "MsBackendMemoryOldSpectrum", function(object, field, returnValue) {
    switch(field,
              "msLevel" = lapply(spectra, msLevel),
              "precursorCharge" = lapply(spectra, preccursorCharge),
               # ...
              rep_len(returnValue, length(object))
    )
}
```

**Comment by lgatto** [comment]
**General comment** I think that  we should drop the `header` name and concept completely. This was something that is linked to the `mzR` backend implementation, but isn't necessary relevant semantically, The name should not be replaced by `spectraData`. 

But, unless I'm missing something, I don't think we can have any implementations for `MsBackend`. The above only makes sense of there's a `spectraData` (`header`). There is no guarantee that one exists for a backend, and first calling `spectraData` (`header`) to create the `DataFrame` and then extracting the column might be expensive. The above could be implemented for `MsBackendDataFrame`.

**Comment by jorainer** [comment]
Note: the https://github.com/lgatto/Spectra/blob/jomaster/R/MsBackendDataFrame-functions.R#L143-L153 function somehow picks the idea from @sgibb up. 

Regarding the implementations for `MsBackend`, yes, we have them. I added all methods there with a `stop`, so, if a backend inheriting from `MsBackend` does not implement a certain method it will stop. That way I sort of wanted to force backend developers to implement all these methods.

And among these methods there is also a `spectraData` as listed in #4. The `MsBackendDataFrame` (in PR #16) implements that method, which I believe might be really helpful (and allows to specify the columns that should be returned - also in-line with @sgibb 's proposal above).

**Comment by lgatto** [comment]
Yes, I like the default implementations that throw an error if the backend doesn't provide one.

As for `spectraData`, I want to clarify that all backends will **have to provide one**, but it might need to be constructed by the backend (i.e. it might not exist as a unique table).

**Comment by jorainer** [comment]
Closing as it seems to be solved/settled by now.
